Repository planetarium/bencodex.net, pull requests merged in 2020-01, with the labels that each got.

#11 Fix Dictionary.Add(byte[], IEnumerable<IValue>)
  Bencodex.Tests/Types/DictionaryTest.cs
  Bencodex/Types/Dictionary.cs
  CHANGES.md
Labels: bug

#13 IValue.Inspection: JSON-like human-readable representation
  Bencodex.Tests/Types/DictionaryTest.cs
  Bencodex.Tests/Types/ListTest.cs
  Bencodex.Tests/Types/ValueTests.cs
  Bencodex/Types/Binary.cs
  Bencodex/Types/Boolean.cs
  Bencodex/Types/Dictionary.cs
  Bencodex/Types/IValue.cs
  Bencodex/Types/Integer.cs
  Bencodex/Types/List.cs
  Bencodex/Types/Null.cs
  Bencodex/Types/Text.cs
  CHANGES.md
  azure-pipelines.yml
Labels: enhancement

#14 Add Binary(string, Encoding) constructor and fix a Binary's unintended mutability
  Bencodex.Tests/Types/BinaryTest.cs
  Bencodex.Tests/Types/ValueTests.cs
  Bencodex/Types/Binary.cs
  CHANGES.md
Labels: bug, enhancement

#17 Fix broken ListTest.Inspect() on Windows
  Bencodex.Tests/Extensions.cs
  Bencodex.Tests/Types/DictionaryTest.cs
  Bencodex.Tests/Types/ListTest.cs
  azure-pipelines.yml
Labels: bug
