Repository planetarium/bencodex.net, pull requests merged in 2023-10, with the labels that each got.

#115 🚀 Release 0.15.0
  CHANGES.md
Labels: Extra Small

#116 🔧 Prepare 0.16.0
  Bencodex.Json/Bencodex.Json.csproj
  Bencodex/Bencodex.csproj
  CHANGES.md
Labels: Extra Small

#117 🧹 Removed obsoleted field Inspection
  Bencodex/Types/Binary.cs
  Bencodex/Types/Boolean.cs
  Bencodex/Types/Dictionary.cs
  Bencodex/Types/IValue.cs
  Bencodex/Types/Integer.cs
  Bencodex/Types/List.cs
  Bencodex/Types/Null.cs
  Bencodex/Types/Text.cs
  CHANGES.md
Labels: Extra Small

#118 🧹 Removed unused parameter from Inspect()
  Bencodex.Tests/CodecTest.cs
  Bencodex.Tests/Types/BinaryTest.cs
  Bencodex.Tests/Types/BooleanTest.cs
  Bencodex.Tests/Types/DictionaryTest.cs
  Bencodex.Tests/Types/IntegerTest.cs
  Bencodex.Tests/Types/ListTest.cs
  Bencodex.Tests/Types/NullTest.cs
  Bencodex.Tests/Types/TextTest.cs
  Bencodex/Types/Binary.cs
  Bencodex/Types/Boolean.cs
  Bencodex/Types/Dictionary.cs
  Bencodex/Types/IValue.cs
  Bencodex/Types/Integer.cs
  Bencodex/Types/List.cs
  Bencodex/Types/Null.cs
  Bencodex/Types/Text.cs
  CHANGES.md
Labels: Medium

#119 Streamline `Boolean` equality
  Bencodex.Tests/Types/BooleanTest.cs
  Bencodex/Types/Boolean.cs
  CHANGES.md
Labels: Small

#120 🚀 Release 0.16.0
  CHANGES.md
Labels: Extra Small, release
